version: '3.8'

services:
  # Main scraper service
  scraper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: savvy-package-index-scraper
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER:-trevorjbennett}
      - GITHUB_REPO=${GITHUB_REPO:-savvy_systems}
    volumes:
      # Mount logs directory to persist logs on host
      - ./logs:/app/logs
    restart: "no"  # Don't restart automatically (for scheduled runs)
    networks:
      - savvy-network

  # Scheduler service (runs the scraper daily at 2 AM)
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: savvy-package-index-scheduler
    depends_on:
      - scraper
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.enabled: "true"
      # Run daily at 2 AM UTC
      ofelia.job-exec.scraper-job.schedule: "0 0 2 * * *"
      ofelia.job-exec.scraper-job.container: "savvy-package-index-scraper"
      ofelia.job-exec.scraper-job.no-overlap: "true"
    restart: unless-stopped
    networks:
      - savvy-network

networks:
  savvy-network:
    driver: bridge
